# Generated by Django 3.0 on 2020-10-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('due_date', models.DateTimeField(verbose_name='date[when] due')),
                ('importance', models.CharField(max_length=20)),
            ],
        ),
    ]
